name: DeadMire
favicon: null
layout_spectrum: 0.43914701230823994
typography_spectrum: 0.7264880400616676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6671136822551489
  lightness: 0.9948212772142142
  saturation: 0.6441038327757269
  rhythmicContrast: 0.1937672032508999
purpose: []
